spring:
  application:
    name: config-server
  profiles:
    active: native # 本地模式
  cloud:
    config:
      server:
        git:
          uri: http://localhost:5001/root/cloud-repo.git
          username: root
          password: 12345678
          default-label: main
        native:
          search-locations: classpath:/cloud-repo # 指定目录方式
server:
  port: 8888
  ssl:
    enabled: true # 开始ssl认证
    key-alias: configServer # 证书别名
    key-store: classpath:configServer.keystore # 证书位置
    key-store-type: JKS # 秘钥库存储类型
    key-store-password: 123456 # 秘钥库口令
    trust-store: classpath:trustStore.keystore # 信任库证书位置
    trust-store-type: JKS # 信任库秘钥存储类型
    trust-store-password: 123456 # 秘钥库口令
eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka