spring:
  application:
    name: eureka-server1
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ENC(Ct/WOPCISoVl1jQ9C0ID1TP9RYecRrR7CDocnTYUvax2ykrY75OrF+1+WAwU0QaF)
  main:
    allow-circular-references: true
server:
  ssl:
    enabled: true # 开始ssl认证
    key-alias: server1 # 证书别名
    key-store: classpath:server1.keystore # 证书位置
    key-store-type: JKS # 秘钥库存储类型
    key-store-password: ENC(Muhq57xdiHA5jJX9pX7zmNz57w4emX2D/XYIXOMEx0LYcTL7RYyadWe2J7GCi9KJ) # 秘钥库口令
    trust-store: classpath:trustStore.keystore # 信任库证书位置
    trust-store-type: JKS # 信任库秘钥存储类型
    trust-store-password: ENC(Muhq57xdiHA5jJX9pX7zmNz57w4emX2D/XYIXOMEx0LYcTL7RYyadWe2J7GCi9KJ) # 秘钥库口令
  port: 7883
#  servlet:
#    context-path: /server1
eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka
  instance:
    secure-port-enabled: true
    non-secure-port-enabled: false
    prefer-ip-address: true
jasypt:
  encryptor:
    password: TKzhc3fz # 设置加密的password信息 类似秘钥？
test:
  password: ENC(Muhq57xdiHA5jJX9pX7zmNz57w4emX2D/XYIXOMEx0LYcTL7RYyadWe2J7GCi9KJ) # 测试数据
#test:
#  password: password:MTIzNDU2 # 测试数据