spring:
  application:
    name: zuul
  redis:
    host: localhost
    port: 6379
server:
  ssl:
    enabled: true # 开始ssl认证
    key-alias: client1 # 证书别名
    key-store: classpath:client1.keystore # 证书位置
    key-store-type: JKS # 秘钥库存储类型
    key-store-password: 123456 # 秘钥库口令
    trust-store: classpath:trustStore.keystore # 信任库证书位置
    trust-store-type: JKS # 信任库秘钥存储类型
    trust-store-password: 123456 # 秘钥库口令
  port: 7886
  servlet:
    context-path: /gateway
eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka
  instance:
    secure-port-enabled: true
    non-secure-port-enabled: false
zuul:
  routes:
    portal:
      path: /portal/**
      sensitiveHeaders:
      serviceId: portal
    client-1:
      path: /client1/**
      sensitiveHeaders:
      serviceId: eureka-client1
    server-1:
      path: /server1/**
      sensitiveHeaders:
      serviceId: eureka-server1